In [30]:
# new_model = tf.keras.models.load_model('lfsr_model.h5')
# new_model.save_weights("mc")
# # model.save("lfsr_model.h5")

In [18]:
import numpy as np

key = np.eye(10, 10).astype(int)
key1 = key[:5]
key2 = key[5:]
print(key1)
print(key2)
print(np.roll(key1, -1, axis=0))

[[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]]
[[0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]
[[0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]]


In [29]:
x = []
for i in range(20):
    # print(key1[0].shape, key1[1].shape)
    nxt1 = key1[0] ^ key1[1]
    nxt2 = key2[0] ^ key2[2]
    key1 = np.roll(key1, -1, axis=0)
    key2 = np.roll(key2, -1, axis=0)
    key1[-1] = nxt1
    key2[-1] = nxt2
    nxt = nxt1 ^ nxt2
    print(nxt)
    x.append(nxt)

[0 1 1 1 1 1 1 0 1 1]
[1 1 1 1 1 1 1 0 0 1]
[1 0 1 1 1 1 1 0 0 0]
[1 0 0 1 1 0 1 1 0 0]
[1 0 0 0 1 0 0 1 1 0]
[1 0 0 0 0 0 0 0 1 1]
[0 1 0 0 0 1 0 1 0 1]
[0 0 1 0 0 1 1 1 1 0]
[0 0 0 1 0 0 1 1 1 1]
[0 0 0 0 1 1 0 0 1 1]
[1 1 0 0 0 1 1 1 0 1]
[0 1 1 0 0 1 1 0 1 0]
[0 0 1 1 0 0 1 1 0 1]
[0 0 0 1 1 1 0 0 1 0]
[1 1 0 0 1 0 1 0 0 1]
[1 0 1 0 0 1 0 0 0 0]
[0 1 0 1 0 0 1 0 0 0]
[0 0 1 0 1 0 0 1 0 0]
[1 1 0 1 0 0 0 0 1 0]
[0 1 1 0 1 0 0 0 0 1]


In [27]:
for i in range(1024):
    ind = np.binary_repr(i, width=10)
    # print(ind)
    total = np.zeros(10, dtype=int)
    for j in range(10):
        if ind[j] == "1":
            total = total ^ x[j]
    if np.array_equal(total, x[10]):
        # for j in range(10):
        #     if ind[j] == "1":
        #         print(j, end=" ")
        print(ind)

1111001100


In [30]:
print(x[0] ^ x[1] ^ x[2] ^ x[3] ^ x[6] ^ x[7], x[10])

[1 1 0 0 0 1 1 1 0 1] [1 1 0 0 0 1 1 1 0 1]


In [31]:
print(x[0 + 3] ^ x[1 + 3] ^ x[2 + 3] ^ x[3 + 3] ^ x[6 + 3] ^ x[7 + 3], x[10 + 3])

[0 0 0 1 1 1 0 0 1 0] [0 0 0 1 1 1 0 0 1 0]


In [1]:
ln1 = 10
ln2 = 11
ln3 = 0
import numpy as np

ln = ln1 + ln2 + ln3
key = np.eye(ln, ln).astype(int)
key1 = key[:ln1]
key2 = key[ln1 : ln1 + ln2]
key3 = key[ln1 + ln2 :]
print(key1)
print(key2)
print(key3)

x = []
for i in range(ln + 1):
    # print(key1[0].shape, key1[1].shape)
    nxt1 = key1[0] ^ key1[6] ^ key1[7] ^ key1[9]
    nxt2 = key2[0] ^ key2[9]
    # nxt3 = key3[0] ^ key3[6] ^ key3[8] ^ key3[11]
    key1 = np.roll(key1, -1, axis=0)
    key2 = np.roll(key2, -1, axis=0)
    # key3 = np.roll(key3, -1, axis=0)
    key1[-1] = nxt1
    key2[-1] = nxt2
    # key3[-1] = nxt3
    nxt = nxt1 ^ nxt2  # ^ nxt3
    print(nxt)
    x.append(nxt)

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]
[]
[1 0 0 0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 0 1 0]
[1 1 0

In [5]:
ln = ln1 + ln2 + ln3
for i in range(2 ** (ln)):
    ind = np.binary_repr(i, width=ln)
    # if i % 1000 == 0:
    #     print(ind, end="\r")
    # print(ind, end="\r")
    # print(ind)
    total = np.zeros(ln1 + ln2 + ln3, dtype=int)
    for j in range(ln):
        if ind[j] == "1":
            total = total ^ x[j]
    if np.array_equal(total, x[ln]):
        # for j in range(10):
        #     if ind[j] == "1":
        #         print(j, end=" ")
        print(ind)

KeyboardInterrupt: 